import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/componenets/ui/navbar";

// const inter = Inter({subnets: ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
      >
        <div className="relative w-full items-center justify-center">
          <Navbar />
        </div>
      </body>
    </html>
  );
}
